repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
      exclude: setup.cfg
    - id: end-of-file-fixer
    - id: check-yaml

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.4
  hooks:
    - id: ruff-check
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1
  hooks:
  - id: mypy
    verbose: true
    args: [--show-error-codes, --ignore-missing-imports]
    additional_dependencies: ['types-requests', 'types-PyYAML']
